codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2% 
    patch:
      default:
        threshold: 10%

ignore:
  - "src/Presentation/**/Views/*.php"
  - "src/Presentation/**/Pages/*.php"
  - "src/Languages/*.php"
  - "src/bootstrap.php"
  - "src/plugin.php"
  - "src/courtly.php"
