services:
  wordpress:
    image: wordpress:latest
    container_name: courtly_wp
    restart: always
    ports:
      - "8090:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: courtly_user
      WORDPRESS_DB_PASSWORD: courtly_pass
      WORDPRESS_DB_NAME: courtly_db
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);
        @ini_set('display_errors', 0);
        define('XDEBUG_CONFIG', 'client_host=host.docker.internal');
        define('XDEBUG_MODE', 'debug');
        define('XDEBUG_SESSION', 'wordpress');
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./docker/wp-content:/var/www/html/wp-content
      - ./src:/var/www/html/wp-content/plugins/courtly

  db:
    image: mysql:5.7
    container_name: courtly_db
    restart: always
    environment:
      MYSQL_DATABASE: courtly_db
      MYSQL_USER: courtly_user
      MYSQL_PASSWORD: courtly_pass
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: courtly_phpmyadmin
    restart: always
    ports:
      - "8091:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword

volumes:
  db_data:
