name: Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get short commit hash
        id: get_hash
        run: echo "short_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Read version from courtly.php
        id: get_version
        run: |
          version=$(grep -oP 'Version:\s*\K[\d.]+' src/courtly.php)
          echo "version=$version" >> $GITHUB_OUTPUT
          
      - name: Configure Git identity
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
      - name: Create tag (if not exists)
        id: create_tag
        run: |
          short_hash=$(git rev-parse --short HEAD)
          version=${{ steps.get_version.outputs.version }}
          tag="v${version}-${short_hash}"
      
          if git rev-parse "$tag" >/dev/null 2>&1; then
            echo "Tag $tag already exists. Skipping creation."
          else
            git tag -a "$tag" -m "Release $tag"
            git push origin "$tag"
          fi

          echo "tag=$tag" >> $GITHUB_OUTPUT
          
      - name: Install gettext
        run: sudo apt-get update && sudo apt-get install -y gettext

      - name: Compile .po to .mo files
        working-directory: src/languages
        run: |
          for file in *.po; do
            msgfmt "$file" -o "${file%.po}.mo"
          done

      - name: Validate .mo files
        working-directory: src/languages
        run: |
          po_count=$(ls -1 *.po | wc -l)
          mo_count=$(ls -1 *.mo | wc -l)
          if [ "$po_count" -ne "$mo_count" ]; then
            echo "Mismatch between .po and .mo files. Failing."
            exit 1
          fi

      - name: Build courtly plugin zip (WordPress structure)
        run: |
          mkdir -p build/courtly
          cp -r src/* build/courtly/
          cd build
          zip -r courtly-v${{ steps.get_version.outputs.version }}-${{ steps.get_hash.outputs.short_hash }}.zip courtly

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: courtly-v${{ steps.get_version.outputs.version }}-${{ steps.get_hash.outputs.short_hash }}.zip
          path: build/courtly-v${{ steps.get_version.outputs.version }}-${{ steps.get_hash.outputs.short_hash }}.zip
