name: Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read version from courtly.php
        id: get_version
        run: |
          version=$(grep -oP 'Version:\s*\K[\d.]+' src/courtly.php)
          echo "version=$version" >> $GITHUB_OUTPUT
          
      - name: Configure Git identity
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
      - name: Create tag (if not exists)
        id: create_tag
        run: |
          short_hash=$(git rev-parse --short HEAD)
          version=${{ steps.get_version.outputs.version }}
          tag="v${version}-${short_hash}"
      
          if git rev-parse "$tag" >/dev/null 2>&1; then
            echo "Tag $tag already exists. Skipping creation."
          else
            git tag -a "$tag" -m "Release $tag"
            git push origin "$tag"
          fi

          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Generate courtly.zip artifact
        run: |
          zip -r courtly-v${{ steps.get_version.outputs.version }}-${{ github.sha::7 }}.zip src

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: courtly-v${{ steps.get_version.outputs.version }}-${{ github.sha::7 }}.zip
          path: courtly-v${{ steps.get_version.outputs.version }}-${{ github.sha::7 }}.zip
