name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 0.0.1)'
        required: true
      notes:
        description: 'Optional release notes'
        required: false

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fail if GitHub release already exists
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if gh release view "v${{ github.event.inputs.version }}" >/dev/null 2>&1; then
            echo "❌ Release v${{ github.event.inputs.version }} already exists. Please delete it manually to re-release."
            exit 1
          fi

      - name: Install gettext
        run: sudo apt-get update && sudo apt-get install -y gettext

      - name: Compile .po to .mo files
        working-directory: src/languages
        run: |
          for file in *.po; do
            msgfmt "$file" -o "${file%.po}.mo"
          done

      - name: Validate .mo files
        working-directory: src/languages
        run: |
          po_count=$(ls -1 *.po | wc -l)
          mo_count=$(ls -1 *.mo | wc -l)
          if [ "$po_count" -ne "$mo_count" ]; then
            echo "Mismatch between .po and .mo files. Failing."
            exit 1
          fi

      - name: Generate courtly.zip with plugin root
        run: |
          mkdir -p build/courtly
          cp -r src/* build/courtly/
          cd build
          zip -r courtly.zip courtly

      - name: Prepare release notes
        run: |
          if [ -n "${{ github.event.inputs.notes }}" ]; then
            echo "${{ github.event.inputs.notes }}" > notes.md
          else
            echo "Manual release for version ${{ github.event.inputs.version }}" > notes.md
          fi

      - name: Create Git tag (only if it doesn't exist)
        run: |
          tag="v${{ github.event.inputs.version }}"
          if git rev-parse "$tag" >/dev/null 2>&1; then
            echo "✅ Tag $tag already exists. Skipping tag creation."
          else
            git tag "$tag"
            git push origin "$tag"
          fi

      - name: Create GitHub release using gh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ github.event.inputs.version }} \
            build/courtly.zip \
            --title "Release v${{ github.event.inputs.version }}" \
            --notes-file notes.md
