name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 0.0.1)'
        required: true
      notes:
        description: 'Optional release notes'
        required: false

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if tag exists
        run: |
          if git rev-parse "v${{ github.event.inputs.version }}" >/dev/null 2>&1; then
            echo "Tag v${{ github.event.inputs.version }} already exists"
            exit 1
          fi

      - name: Generate courtly.zip
        run: zip -r courtly.zip src

      - name: Extract release notes
        id: changelog
        run: |
          if [ -n "${{ github.event.inputs.notes }}" ]; then
            echo "${{ github.event.inputs.notes }}" > notes.md
          else
            sed -n "/## \[${{ github.event.inputs.version }}\]/,/^## /p" CHANGELOG.md | sed '$d' > notes.md
          fi

      - name: Create GitHub release using gh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ github.event.inputs.version }} \
            courtly.zip \
            --title "Release v${{ github.event.inputs.version }}" \
            --notes-file notes.md
